### ISSUE TITLE
Stuck in Login page

### ISSUE THREAD

**Issue by MonishESGit** [BetaPack/MovieRecommender#1]
@adii711 While testing your new feature, I'm stuck on the login page.

1. I created a new account
2. Got the OTP via email
3. Pasted the OTP and verified the email
4. But then while logging in I'm stuck at the login page. Clicking on the login button does not take me anywhere

Can you work on this issue?

**Comment by adii711** [comment]
@MonishESGit T
Thank you for your feedback regarding the login issue. After investigating, I discovered that the problem stemmed from user details not being stored correctly in the CSV file. This prevented the system from recognizing new user data during login. I have addressed this issue, and the login functionality should now work as intended. Please try again and let me know if you encounter any further problems.

**Comment by adii711** [comment]
To log in, please enter your registered email and password on the login page. If you have just created an account, ensure you have verified your email by entering the OTP sent to your email address. After successful verification, you should be able to log in without any issues. If you continue to experience problems, please reach out for further assistance.

Best,
@adii711
